/*----------------------\
   LevelInfo by Tekish
\----------------------*/

#library "levelinfo"
#include "zcommon.acs"
#include "levelassign.acs"

#define LI_COLOR_DARK	"u"
#define LI_COLOR_MORPH	"s"
#define LI_COLOR_OXYGEN	"v"
#define LI_COLOR_POISON	"q"
#define LI_COLOR_RADS	"x"
#define LI_COLOR_VALUE	"k"
#define LI_MAXNUMBER	99999
#define LI_MAXTIME		356400
#define LI_POISONTICS	10
#define LI_RADSDAMAGE	560
#define LI_REFRESH		3
#define LI_TICRATE		35

bool highlight[LI_TOTAL];
str text[LI_TOTAL];
str value[LI_TOTAL][3];

/*------------\
   Functions
\------------*/

function void composevalue(int showpercentage)
{
	for (int i = 0; i < 3; i++)
	{
		if (strcmp(text[i], "") && showpercentage != 2)
		{
			if (showpercentage == 1 && strcmp(value[i][2], ""))
				value[i][0] = strparam(s:value[i][0], s:"/", s:value[i][1], s:" (", s:value[i][2], s:")");
			else
				value[i][0] = strparam(s:value[i][0], s:"/", s:value[i][1]);
		}
	}
}

function str coloredtext(str color, str string, bool addcolor)
{
	if (addcolor)
		return strparam(s:"\c", s:color, s:string, s:"\c-");

	return string;
}

function str formattime(int seconds)
{
	if (seconds < 0)
		seconds = -seconds;

	if (seconds < 3600)
		return strparam(d:seconds / 60, s:":", d:(seconds % 60) / 10, d:seconds % 10);

	return strparam(d:seconds / 3600, s:":", d:((seconds / 60) % 60) / 10, d:((seconds / 60) % 60) % 10, s:":", d:(seconds % 60) / 10, d:seconds % 10);
}

function int maxnumber(int number, int maximum)
{
	if (number > maximum)
		return maximum;

	return number;
}

function str newline(str string)
{
	if (strcmp(string, ""))
		return strparam(s:string, s:"\n");

	return string;
}

/*-------\
   Core
\-------*/

function void levelinfo(void)
{
	if (getcvar("li_visible"))
	{
		bool highlightvalue = getcvar("li_highlightvalue");
		bool showlevelinfo = getcvar("li_showlevelinfo");
		bool showtime = getcvar("li_showtime");
		int showpercentage = getcvar("li_showpercentage");
		int i, items, itemstotal, monsters, monsterstotal, secrets, secretstotal;
		str percentage = "", texts = "", values = "";

		if (showpercentage < 0 || showpercentage > 2)
			showpercentage = 0;

		for (i = 0; i < LI_TOTAL; i++)
		{
			highlight[i] = false;
			text[i] = "";
			value[i][0] = "";
			value[i][1] = "";
			value[i][2] = "";
		}

		if (showlevelinfo)
		{
			monsters = maxnumber(getlevelinfo(LEVELINFO_KILLED_MONSTERS), LI_MAXNUMBER);
			monsterstotal = maxnumber(getlevelinfo(LEVELINFO_TOTAL_MONSTERS), LI_MAXNUMBER);
			items = maxnumber(getlevelinfo(LEVELINFO_FOUND_ITEMS), LI_MAXNUMBER);
			itemstotal = maxnumber(getlevelinfo(LEVELINFO_TOTAL_ITEMS), LI_MAXNUMBER);
			secrets = maxnumber(getlevelinfo(LEVELINFO_FOUND_SECRETS), LI_MAXNUMBER);
			secretstotal = maxnumber(getlevelinfo(LEVELINFO_TOTAL_SECRETS), LI_MAXNUMBER);

			if (monsterstotal)
			{
				if (highlightvalue && monsters >= monsterstotal)
					highlight[0] = true;

				text[0] = "Kills";

				if (showpercentage != 2)
				{
					value[0][0] = strparam(d:monsters);
					value[0][1] = strparam(d:monsterstotal);
				}

				if (showpercentage)
				{
					percentage = strparam(d:100 * monsters / monsterstotal, s:"%");

					if (showpercentage == 2)
						value[0][0] = percentage;
					else
						value[0][2] = percentage;
				}
			}

			if (itemstotal)
			{
				if (highlightvalue && items >= itemstotal)
					highlight[1] = true;

				text[1] = "Items";

				if (showpercentage != 2)
				{
					value[1][0] = strparam(d:items);
					value[1][1] = strparam(d:itemstotal);
				}

				if (showpercentage)
				{
					percentage = strparam(d:100 * items / itemstotal, s:"%");

					if (showpercentage == 2)
						value[1][0] = percentage;
					else
						value[1][2] = percentage;
				}
			}

			if (secretstotal)
			{
				if (highlightvalue && secrets >= secretstotal)
					highlight[2] = true;

				text[2] = "Secrets";

				if (showpercentage != 2)
				{
					value[2][0] = strparam(d:secrets);
					value[2][1] = strparam(d:secretstotal);
				}

				if (showpercentage)
				{
					percentage = strparam(d:100 * secrets / secretstotal, s:"%");

					if (showpercentage == 2)
						value[2][0] = percentage;
					else
						value[2][2] = percentage;
				}
			}

			if (showtime && (itemstotal || monsterstotal || secretstotal))
			{
				bool showpar = getcvar("li_showpar");
				bool showtotaltime = getcvar("li_showtotaltime");
				int timemap = maxnumber(timer() / LI_TICRATE, LI_MAXTIME);
				int timepar = maxnumber(getlevelinfo(LEVELINFO_PAR_TIME), LI_MAXTIME);

				if (highlightvalue && timepar >= timemap)
					highlight[3] = true;

				text[3] = "Time";
				value[3][0] = formattime(timemap);

				if (showpar && timepar)
				{
					text[4] = "Par";
					value[4][0] = formattime(timepar);
				}
				else
				{
					showpar = false;
				}

				if (showtotaltime)
				{
					int timetotal = scriptcall("levelinfobridge", "gettotaltime");

					if (timetotal)
					{
						text[5] = "Total";
						value[5][0] = formattime(maxnumber(timetotal / LI_TICRATE, LI_MAXTIME));
					}
				}
			}
			else
			{
				showtime = false;
			}
		}

		bool cantdrown;
		bool showberserk = getcvar("li_showberserk");
		bool showpowerups = getcvar("li_showpowerups");
		int a = 6;

		if (showpowerups)
		{
			for (i = 0; i < LI_POWERUPS; i++)
			{
				powerups[i][1] = false;

				if (powerups[i][0] && checkinventory(powerupsvalues[i][0]))
				{
					if (i == 0)
					{
						if (showberserk)
						{
							powerups[i][1] = true;
							text[a] = powerupsvalues[i][1];
							value[a][0] = formattime(maxnumber(getactorpoweruptics(0, powerupsvalues[i][0]) / LI_TICRATE, LI_MAXTIME));
						}
					}
					else
					{
						if (!strcmp(powerupsvalues[i][1], "Immune") || !strcmp(powerupsvalues[i][1], "Suit"))
							cantdrown = true;

						powerups[i][1] = true;
						text[a] = powerupsvalues[i][1];
						value[a][0] = formattime(maxnumber(fixeddiv((getactorpoweruptics(0, powerupsvalues[i][0]) << 16) + (LI_TICRATE << 16), LI_TICRATE << 16) >> 16, LI_MAXTIME));
					}
				}

				a++;
			}
		}

		bool havemorph, haveoxygen, havepoison, haverads;
		bool showhazards = getcvar("li_showhazards");
		bool showoxygen = getcvar("li_showoxygen");

		if (showoxygen && !cantdrown && (classifyactor(0) & ACTOR_ALIVE) && getactorproperty(0, APROP_Waterlevel) == 3)
		{
			int oxygen = maxnumber(fixeddiv((getairsupply(playernumber()) << 16) + (LI_TICRATE << 16), LI_TICRATE << 16) >> 16, LI_MAXTIME);

			if (oxygen < 0)
				oxygen = 0;

			haveoxygen = true;
			text[LI_TOTAL - 3] = "Oxygen";
			value[LI_TOTAL - 3][0] = formattime(oxygen);
		}

		if (showhazards)
		{
			int morph = scriptcall("levelinfobridge", "getmorph");
			int poison = scriptcall("levelinfobridge", "getpoison");
			int rads = scriptcall("levelinfobridge", "gethazard");

			if (morph)
			{
				havemorph = true;
				text[LI_TOTAL - 4] = "Morph";
				value[LI_TOTAL - 4][0] = formattime(maxnumber(fixeddiv((morph << 16) + (LI_TICRATE << 16), LI_TICRATE << 16) >> 16, LI_MAXTIME));
			}

			if (poison)
			{
				havepoison = true;
				text[LI_TOTAL - 2] = "Poison";
				value[LI_TOTAL - 2][0] = formattime(maxnumber(fixeddiv((poison << 16) + (LI_POISONTICS << 16), LI_POISONTICS << 16) >> 16, LI_MAXTIME));
			}

			if (rads)
			{
				str radsvalue = "";

				if (rads < LI_RADSDAMAGE)
					radsvalue = strparam(d:99 * rads / LI_RADSDAMAGE + 1, s:"%");
				else
					radsvalue = formattime(maxnumber(fixeddiv((rads - LI_RADSDAMAGE << 16) + (LI_TICRATE << 16), LI_TICRATE << 16) >> 16, LI_MAXTIME));

				haverads = true;
				text[LI_TOTAL - 1] = "Rads";
				value[LI_TOTAL - 1][0] = radsvalue;
			}
		}

		int abbreviate = getcvar("li_abbreviate");

		if (abbreviate < 0 || abbreviate > 8)
			abbreviate = 4;

		if (havemorph || haveoxygen || havepoison || haverads || showlevelinfo || showpowerups)
		{
			if (abbreviate)
			{
				for (i = 0; i < LI_TOTAL; i++)
					text[i] = strleft(text[i], abbreviate);
			}

			composevalue(showpercentage);
		}

		if (showlevelinfo)
		{
			if (monsterstotal)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[0], true));
				values = strparam(s:newline(values), s:coloredtext(LI_COLOR_VALUE, value[0][0], highlight[0]));
			}

			if (itemstotal)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[1], true));
				values = strparam(s:newline(values), s:coloredtext(LI_COLOR_VALUE, value[1][0], highlight[1]));
			}

			if (secretstotal)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[2], true));
				values = strparam(s:newline(values), s:coloredtext(LI_COLOR_VALUE, value[2][0], highlight[2]));
			}

			if (showtime)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[3], true));
				values = strparam(s:newline(values), s:coloredtext(LI_COLOR_VALUE, value[3][0], highlight[3]));

				if (showpar)
				{
					texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[4], true));
					values = strparam(s:newline(values), s:coloredtext(LI_COLOR_VALUE, value[4][0], highlight[3]));
				}

				if (showtotaltime)
				{
					texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_DARK, text[5], true));
					values = strparam(s:newline(values), s:value[5][0]);
				}
			}
		}

		if (showpowerups)
		{
			bool activepowerup = false;
			a = 6;

			for (i = 0; i < LI_POWERUPS; i++)
			{
				if (powerups[i][1])
				{
					if (!activepowerup)
					{
						activepowerup = true;
						texts = newline(texts);
						values = newline(values);
					}

					texts = strparam(s:newline(texts), s:coloredtext(powerupsvalues[i][2], text[a], true));
					values = strparam(s:newline(values), s:value[a][0]);
				}

				a++;
			}
		}

		if (havemorph || haveoxygen || havepoison || haverads)
		{
			texts = newline(texts);
			values = newline(values);

			if (havemorph)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_MORPH, text[LI_TOTAL - 4], true));
				values = strparam(s:newline(values), s:value[LI_TOTAL - 4][0]);
			}

			if (haveoxygen)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_OXYGEN, text[LI_TOTAL - 3], true));
				values = strparam(s:newline(values), s:value[LI_TOTAL - 3][0]);
			}

			if (havepoison)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_POISON, text[LI_TOTAL - 2], true));
				values = strparam(s:newline(values), s:value[LI_TOTAL - 2][0]);
			}

			if (haverads)
			{
				texts = strparam(s:newline(texts), s:coloredtext(LI_COLOR_RADS, text[LI_TOTAL - 1], true));
				values = strparam(s:newline(values), s:value[LI_TOTAL - 1][0]);
			}
		}

		if (strcmp(texts, ""))
		{
			scriptcall("levelinforenderer", "pushrows", texts, values);
		}
		else
		{
			scriptcall("levelinforenderer", "clear");
		}
	}
}

script "levelinfo" (void)
{
	levelinfo();
	delay(LI_REFRESH);
	restart;
}

script "levelinfodeath" DEATH
{
	if (playernumber() != scriptcall("levelinfobridge", "getconsoleplayer"))
		terminate;

	scriptcall("levelinforenderer", "clear");
	acs_namedterminate("levelinfo", 0);
}

script "levelinfoenter" ENTER
{
	if (playernumber() != scriptcall("levelinfobridge", "getconsoleplayer"))
		terminate;

	if (!strcmp("TITLEMAP", strparam(n:PRINTNAME_LEVEL)))
		terminate;

	levelassign(getactorclass(0));
	acs_namedexecute("levelinfo", 0);
}

script "levelinforespawn" RESPAWN
{
	if (playernumber() != scriptcall("levelinfobridge", "getconsoleplayer"))
		terminate;

	if (!strcmp("TITLEMAP", strparam(n:PRINTNAME_LEVEL)))
		terminate;

	acs_namedexecute("levelinfo", 0);
}